language: node_js
node_js:
  - 12
services:
  - docker
script:
  # Build
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy

  # Tag
  - docker tag udagram-api-feed irinagabe/udagram-api-feed:v2
  - docker tag udagram-api-user irinagabe/udagram-api-user:v2
  - docker tag udagram-frontend irinagabe/udagram-frontend:v2
  - docker tag reverseproxy irinagabe/reverseproxy:v2
after_success:
  # Push
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push irinagabe/udagram-api-feed:v2
  - docker push irinagabe/udagram-api-user:v2
  - docker push irinagabe/udagram-frontend:v2
  - docker push irinagabe/reverseproxy:v2
