apiVersion: udagram/v1
kind: Deployment
metadata:
  name: api-user
  labels:
    app: udagram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udagram
  template:
    metadata:
      labels:
        app: udagram
    spec:
      containers:
        - name: udagram-api-user
          image: irinagabe/udagram-api-user:latest
          ports:
            - containerPort: 8080
